// Code generated by "stringer -type Operation -type Option"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OptionDoNotFollowRedirect-0]
}

const _Option_name = "OptionDoNotFollowRedirect"

var _Option_index = [...]uint8{0, 25}

func (i Option) String() string {
	if i < 0 || i >= Option(len(_Option_index)-1) {
		return "Option(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Option_name[_Option_index[i]:_Option_index[i+1]]
}
